FROM golang:1.26.1-alpine3.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /server ./cmd/server/main.go

FROM alpine:latest
COPY --from=builder /server /server
ENTRYPOINT [ "/server" ]