FROM golang:1.26.1-alpine3.23 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /server ./cmd/server/main.go

FROM alpine:3.23
RUN apk add --no-cache ca-certificates \
    && adduser -D -u 10001 gophkeeper
COPY --from=builder /server /server
USER gophkeeper
HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \
    CMD nc -z localhost 50051 || exit 1
ENTRYPOINT ["/server"]
