// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AdminClient is an autogenerated mock type for the AdminClient type
type AdminClient struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: ctx, login
func (_m *AdminClient) DeleteUser(ctx context.Context, login string) error {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdminClient creates a new instance of AdminClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminClient {
	mock := &AdminClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
