// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/F3dosik/GophKeeper/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuthClient is an autogenerated mock type for the AuthClient type
type AuthClient struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, change, secrets
func (_m *AuthClient) ChangePassword(ctx context.Context, change domain.PasswordChange, secrets []domain.ReencryptedSecret) (string, error) {
	ret := _m.Called(ctx, change, secrets)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PasswordChange, []domain.ReencryptedSecret) (string, error)); ok {
		return rf(ctx, change, secrets)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PasswordChange, []domain.ReencryptedSecret) string); ok {
		r0 = rf(ctx, change, secrets)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PasswordChange, []domain.ReencryptedSecret) error); ok {
		r1 = rf(ctx, change, secrets)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, creds, salt, kdf
func (_m *AuthClient) CreateUser(ctx context.Context, creds domain.Credentials, salt []byte, kdf domain.KDFParams) error {
	ret := _m.Called(ctx, creds, salt, kdf)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Credentials, []byte, domain.KDFParams) error); ok {
		r0 = rf(ctx, creds, salt, kdf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSalt provides a mock function with given fields: ctx, login
func (_m *AuthClient) GetSalt(ctx context.Context, login string) ([]byte, domain.KDFParams, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetSalt")
	}

	var r0 []byte
	var r1 domain.KDFParams
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, domain.KDFParams, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) domain.KDFParams); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Get(1).(domain.KDFParams)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, login)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Login provides a mock function with given fields: ctx, creds
func (_m *AuthClient) Login(ctx context.Context, creds domain.Credentials) (string, error) {
	ret := _m.Called(ctx, creds)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Credentials) (string, error)); ok {
		return rf(ctx, creds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Credentials) string); ok {
		r0 = rf(ctx, creds)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Credentials) error); ok {
		r1 = rf(ctx, creds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, allSessions
func (_m *AuthClient) Logout(ctx context.Context, allSessions bool) error {
	ret := _m.Called(ctx, allSessions)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = rf(ctx, allSessions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthClient creates a new instance of AuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthClient {
	mock := &AuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
