// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/F3dosik/GophKeeper/proto/gen"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// PBAuthClient is an autogenerated mock type for the AuthClient type
type PBAuthClient struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, in, opts
func (_m *PBAuthClient) CreateUser(ctx context.Context, in *gen.CreateUserRequest, opts ...grpc.CallOption) (*gen.CreateUserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *gen.CreateUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateUserRequest, ...grpc.CallOption) (*gen.CreateUserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateUserRequest, ...grpc.CallOption) *gen.CreateUserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.CreateUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateUserRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSalt provides a mock function with given fields: ctx, in, opts
func (_m *PBAuthClient) GetSalt(ctx context.Context, in *gen.GetSaltRequest, opts ...grpc.CallOption) (*gen.GetSaltResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSalt")
	}

	var r0 *gen.GetSaltResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetSaltRequest, ...grpc.CallOption) (*gen.GetSaltResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetSaltRequest, ...grpc.CallOption) *gen.GetSaltResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetSaltResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetSaltRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *PBAuthClient) Login(ctx context.Context, in *gen.LoginRequest, opts ...grpc.CallOption) (*gen.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *gen.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.LoginRequest, ...grpc.CallOption) (*gen.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.LoginRequest, ...grpc.CallOption) *gen.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPBAuthClient creates a new instance of PBAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPBAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PBAuthClient {
	mock := &PBAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
