// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/F3dosik/GophKeeper/proto/gen"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// SecretsClient is an autogenerated mock type for the SecretsClient type
type SecretsClient struct {
	mock.Mock
}

// CreateSecret provides a mock function with given fields: ctx, in, opts
func (_m *SecretsClient) CreateSecret(ctx context.Context, in *gen.CreateSecretRequest, opts ...grpc.CallOption) (*gen.CreateSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *gen.CreateSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateSecretRequest, ...grpc.CallOption) (*gen.CreateSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.CreateSecretRequest, ...grpc.CallOption) *gen.CreateSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.CreateSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.CreateSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteSecret provides a mock function with given fields: ctx, in, opts
func (_m *SecretsClient) DeleteSecret(ctx context.Context, in *gen.DeleteSecretRequest, opts ...grpc.CallOption) (*gen.DeleteSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 *gen.DeleteSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteSecretRequest, ...grpc.CallOption) (*gen.DeleteSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.DeleteSecretRequest, ...grpc.CallOption) *gen.DeleteSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DeleteSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.DeleteSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSecret provides a mock function with given fields: ctx, in, opts
func (_m *SecretsClient) GetSecret(ctx context.Context, in *gen.GetSecretRequest, opts ...grpc.CallOption) (*gen.GetSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *gen.GetSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetSecretRequest, ...grpc.CallOption) (*gen.GetSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.GetSecretRequest, ...grpc.CallOption) *gen.GetSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.GetSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.GetSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSecrets provides a mock function with given fields: ctx, in, opts
func (_m *SecretsClient) ListSecrets(ctx context.Context, in *gen.ListSecretsRequest, opts ...grpc.CallOption) (*gen.ListSecretsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 *gen.ListSecretsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ListSecretsRequest, ...grpc.CallOption) (*gen.ListSecretsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ListSecretsRequest, ...grpc.CallOption) *gen.ListSecretsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ListSecretsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.ListSecretsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSecret provides a mock function with given fields: ctx, in, opts
func (_m *SecretsClient) UpdateSecret(ctx context.Context, in *gen.UpdateSecretRequest, opts ...grpc.CallOption) (*gen.UpdateSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 *gen.UpdateSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateSecretRequest, ...grpc.CallOption) (*gen.UpdateSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.UpdateSecretRequest, ...grpc.CallOption) *gen.UpdateSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.UpdateSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.UpdateSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSecretsClient creates a new instance of SecretsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsClient {
	mock := &SecretsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
