// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/F3dosik/GophKeeper/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// SecretsClient is an autogenerated mock type for the SecretsClient type
type SecretsClient struct {
	mock.Mock
}

// CreateSecret provides a mock function with given fields: ctx, blindIndex, data
func (_m *SecretsClient) CreateSecret(ctx context.Context, blindIndex string, data []byte) error {
	ret := _m.Called(ctx, blindIndex, data)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, blindIndex, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSecret provides a mock function with given fields: ctx, blindIndex
func (_m *SecretsClient) DeleteSecret(ctx context.Context, blindIndex string) error {
	ret := _m.Called(ctx, blindIndex)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, blindIndex)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSecret provides a mock function with given fields: ctx, blindIndex
func (_m *SecretsClient) GetSecret(ctx context.Context, blindIndex string) (*domain.Secret, error) {
	ret := _m.Called(ctx, blindIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Secret, error)); ok {
		return rf(ctx, blindIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Secret); ok {
		r0 = rf(ctx, blindIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, blindIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListSecrets provides a mock function with given fields: ctx
func (_m *SecretsClient) ListSecrets(ctx context.Context) ([]*domain.Secret, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 []*domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Secret, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Secret); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSecret provides a mock function with given fields: ctx, blindIndex, data
func (_m *SecretsClient) UpdateSecret(ctx context.Context, blindIndex string, data []byte) error {
	ret := _m.Called(ctx, blindIndex, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, blindIndex, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSecretsClient creates a new instance of SecretsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsClient {
	mock := &SecretsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
