// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminCreateTemporaryUser(arg1) {
  return window['go']['backend']['App']['AdminCreateTemporaryUser'](arg1);
}

export function AdminDeleteUser(arg1) {
  return window['go']['backend']['App']['AdminDeleteUser'](arg1);
}

export function AdminListUsers() {
  return window['go']['backend']['App']['AdminListUsers']();
}

export function AdminRevokeSessions(arg1) {
  return window['go']['backend']['App']['AdminRevokeSessions'](arg1);
}

export function ChangePassword(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['ChangePassword'](arg1, arg2, arg3, arg4);
}

export function CheckServer(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CheckServer'](arg1, arg2, arg3);
}

export function ChooseCACert() {
  return window['go']['backend']['App']['ChooseCACert']();
}

export function ChooseExportFile() {
  return window['go']['backend']['App']['ChooseExportFile']();
}

export function ChooseFile() {
  return window['go']['backend']['App']['ChooseFile']();
}

export function CompletePasswordChange(arg1, arg2) {
  return window['go']['backend']['App']['CompletePasswordChange'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['backend']['App']['CopyToClipboard'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['backend']['App']['DeleteAccount'](arg1);
}

export function DeleteSecret(arg1, arg2) {
  return window['go']['backend']['App']['DeleteSecret'](arg1, arg2);
}

export function ExportFile(arg1) {
  return window['go']['backend']['App']['ExportFile'](arg1);
}

export function ExportVault(arg1) {
  return window['go']['backend']['App']['ExportVault'](arg1);
}

export function GeneratePassphrase(arg1) {
  return window['go']['backend']['App']['GeneratePassphrase'](arg1);
}

export function GeneratePassword(arg1) {
  return window['go']['backend']['App']['GeneratePassword'](arg1);
}

export function GetSecret(arg1, arg2) {
  return window['go']['backend']['App']['GetSecret'](arg1, arg2);
}

export function GetState() {
  return window['go']['backend']['App']['GetState']();
}

export function ImportVault(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ImportVault'](arg1, arg2, arg3);
}

export function ListSecrets() {
  return window['go']['backend']['App']['ListSecrets']();
}

export function Lock() {
  return window['go']['backend']['App']['Lock']();
}

export function Logout(arg1) {
  return window['go']['backend']['App']['Logout'](arg1);
}

export function Register(arg1, arg2) {
  return window['go']['backend']['App']['Register'](arg1, arg2);
}

export function SaveSecret(arg1, arg2) {
  return window['go']['backend']['App']['SaveSecret'](arg1, arg2);
}

export function SaveSettings(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['SaveSettings'](arg1, arg2, arg3, arg4);
}

export function SignIn(arg1, arg2) {
  return window['go']['backend']['App']['SignIn'](arg1, arg2);
}

export function Unlock(arg1) {
  return window['go']['backend']['App']['Unlock'](arg1);
}
