// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AdminCreateTemporaryUser(arg1:string):Promise<backend.TemporaryUser>;

export function AdminDeleteUser(arg1:string):Promise<void>;

export function AdminListUsers():Promise<Array<backend.UserRow>>;

export function AdminRevokeSessions(arg1:string):Promise<void>;

export function ChangePassword(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function CheckServer(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function ChooseCACert():Promise<string>;

export function ChooseFile():Promise<backend.ChosenFile>;

export function CompletePasswordChange(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteSecret(arg1:string,arg2:string):Promise<void>;

export function ExportFile(arg1:string):Promise<string>;

export function GeneratePassphrase(arg1:number):Promise<backend.Generated>;

export function GeneratePassword(arg1:backend.GeneratorOptions):Promise<backend.Generated>;

export function GetSecret(arg1:string,arg2:string):Promise<backend.Secret>;

export function GetState():Promise<backend.State>;

export function ListSecrets():Promise<Array<backend.SecretSummary>>;

export function Lock():Promise<void>;

export function Logout(arg1:boolean):Promise<void>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function SaveSecret(arg1:backend.SecretInput,arg2:boolean):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<void>;

export function SignIn(arg1:string,arg2:string):Promise<boolean>;

export function Unlock(arg1:string):Promise<void>;
