// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/F3dosik/GophKeeper/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

// DeleteUser provides a mock function with given fields: ctx, login
func (_m *AdminService) DeleteUser(ctx context.Context, login string) error {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: ctx, login
func (_m *AdminService) GetUser(ctx context.Context, login string) (*domain.UserInfo, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserInfo, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserInfo); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUsers provides a mock function with given fields: ctx, pageToken, pageSize
func (_m *AdminService) ListUsers(ctx context.Context, pageToken string, pageSize int) (*domain.UserPage, error) {
	ret := _m.Called(ctx, pageToken, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *domain.UserPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*domain.UserPage, error)); ok {
		return rf(ctx, pageToken, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *domain.UserPage); ok {
		r0 = rf(ctx, pageToken, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, pageToken, pageSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokeSessions provides a mock function with given fields: ctx, login
func (_m *AdminService) RevokeSessions(ctx context.Context, login string) error {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
