// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/F3dosik/GophKeeper/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, userID, change, secrets
func (_m *AuthService) ChangePassword(ctx context.Context, userID uuid.UUID, change domain.PasswordChange, secrets domain.SecretIterator) (string, error) {
	ret := _m.Called(ctx, userID, change, secrets)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.PasswordChange, domain.SecretIterator) (string, error)); ok {
		return rf(ctx, userID, change, secrets)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.PasswordChange, domain.SecretIterator) string); ok {
		r0 = rf(ctx, userID, change, secrets)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.PasswordChange, domain.SecretIterator) error); ok {
		r1 = rf(ctx, userID, change, secrets)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, reg
func (_m *AuthService) Create(ctx context.Context, reg domain.Registration) (*time.Time, error) {
	ret := _m.Called(ctx, reg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Registration) (*time.Time, error)); ok {
		return rf(ctx, reg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Registration) *time.Time); ok {
		r0 = rf(ctx, reg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Registration) error); ok {
		r1 = rf(ctx, reg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSalt provides a mock function with given fields: ctx, login
func (_m *AuthService) GetSalt(ctx context.Context, login string) ([]byte, domain.KDFParams, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetSalt")
	}

	var r0 []byte
	var r1 domain.KDFParams
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, domain.KDFParams, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) domain.KDFParams); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Get(1).(domain.KDFParams)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, login)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Login provides a mock function with given fields: ctx, login, authKey
func (_m *AuthService) Login(ctx context.Context, login string, authKey []byte) (domain.LoginResult, error) {
	ret := _m.Called(ctx, login, authKey)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 domain.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (domain.LoginResult, error)); ok {
		return rf(ctx, login, authKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) domain.LoginResult); ok {
		r0 = rf(ctx, login, authKey)
	} else {
		r0 = ret.Get(0).(domain.LoginResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, login, authKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, userID, jti, expiresAt, allSessions
func (_m *AuthService) Logout(ctx context.Context, userID uuid.UUID, jti uuid.UUID, expiresAt time.Time, allSessions bool) error {
	ret := _m.Called(ctx, userID, jti, expiresAt, allSessions)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, bool) error); ok {
		r0 = rf(ctx, userID, jti, expiresAt, allSessions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
