// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/F3dosik/GophKeeper/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SecretRepository is an autogenerated mock type for the SecretRepository type
type SecretRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, secret
func (_m *SecretRepository) Create(ctx context.Context, secret *domain.Secret) error {
	ret := _m.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Secret) error); ok {
		r0 = rf(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, userID, blindIndex
func (_m *SecretRepository) Delete(ctx context.Context, userID uuid.UUID, blindIndex string) error {
	ret := _m.Called(ctx, userID, blindIndex)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, blindIndex)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByBlindIndex provides a mock function with given fields: ctx, userID, blindIndex
func (_m *SecretRepository) GetByBlindIndex(ctx context.Context, userID uuid.UUID, blindIndex string) (*domain.Secret, error) {
	ret := _m.Called(ctx, userID, blindIndex)

	if len(ret) == 0 {
		panic("no return value specified for GetByBlindIndex")
	}

	var r0 *domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.Secret, error)); ok {
		return rf(ctx, userID, blindIndex)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.Secret); ok {
		r0 = rf(ctx, userID, blindIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, blindIndex)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *SecretRepository) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.Secret, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Secret, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Secret); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, secret
func (_m *SecretRepository) Update(ctx context.Context, secret *domain.Secret) error {
	ret := _m.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Secret) error); ok {
		r0 = rf(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSecretRepository creates a new instance of SecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretRepository {
	mock := &SecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
