// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// TokenRepository is an autogenerated mock type for the TokenRepository type
type TokenRepository struct {
	mock.Mock
}

// IsActive provides a mock function with given fields: ctx, userID, tokenVersion, jti
func (_m *TokenRepository) IsActive(ctx context.Context, userID uuid.UUID, tokenVersion int, jti uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID, tokenVersion, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID, tokenVersion, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID, tokenVersion, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, uuid.UUID) error); ok {
		r1 = rf(ctx, userID, tokenVersion, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Revoke provides a mock function with given fields: ctx, jti, expiresAt
func (_m *TokenRepository) Revoke(ctx context.Context, jti uuid.UUID, expiresAt time.Time) error {
	ret := _m.Called(ctx, jti, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, jti, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeAll provides a mock function with given fields: ctx, userID
func (_m *TokenRepository) RevokeAll(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RevokeAllByLogin provides a mock function with given fields: ctx, login
func (_m *TokenRepository) RevokeAllByLogin(ctx context.Context, login string) error {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByLogin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTokenRepository creates a new instance of TokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenRepository {
	mock := &TokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
